[package]
name = "chip-8"
version = "0.1.0"
authors = ["Adam Hess <adamhess1991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.12"
